# picolibc is needed for the "_chk" functions
CONFIG_PICOLIBC=y
#CONFIG_PICOLIBC_IO_SUPPORT=y

# =n because i want to controll it with Cmake and not with kconfig
CONFIG_STACK_CANARIES=n

CONFIG_MAIN_STACK_SIZE=4096
